pipeline {
    agent any

    stages {
        stage('Get Code') {
            steps {
                deleteDir()
                git branch: "develop", url: "https://github.com/franbecpin/todo-list-aws.git"                
            }
        } 
        
        stage ('Static Test'){
            steps{
                catchError(buildResult: 'UNSTABLE', stageResult: 'FAILURE') {
                    sh'''
                        export PYTHONPATH="$WORKSPACE/src"
                        flake8 --version
                        flake8 --format=pylint --exit-zero src > flake8.out
                    '''
                    recordIssues sourceCodeRetention: 'LAST_BUILD', tools: [flake8(pattern: 'flake8.out')]
                    

                }
            }
        }
        
        stage('Security'){
            steps{
                catchError(buildResult: 'UNSTABLE', stageResult: 'FAILURE') {
               
                    sh'''
                        export PATH="$HOME/.local/bin:$PATH"
                        #!/bin/bash
                        set -euxo pipefail
                        python3 -m pip install --user --upgrade bandit
                        export PATH="$HOME/.local/bin:$PATH"
                        bandit -r .
                        
                    '''
                    recordIssues sourceCodeRetention: 'LAST_BUILD', tools: [pyLint(pattern: 'bandit.out')]
                     
                    
                }   
            }
        }
    }
}