pipeline {
    agent any
    stages {
        stage('Get Code') {
            steps {
                deleteDir()
                git branch: "develop", url: "https://github.com/franbecpin/todo-list-aws.git"                
            }
        } 
        
        stage ('Static Test'){
            steps{
                catchError(buildResult: 'UNSTABLE', stageResult: 'FAILURE') {
                    sh'''
                        export PYTHONPATH="$WORKSPACE/src"
                        flake8 --version
                    '''
                }
            }
        }    
    }
}