pipeline 
{
    agent any

    stages 
    {
        stage('Get Code') 
        {
            steps 
            {
                deleteDir()
                git branch: "develop", url: "https://github.com/franbecpin/todo-list-aws.git"                
            }
        } 
        
        stage ('Static Test')
        {
            steps
            {
                catchError(buildResult: 'UNSTABLE', stageResult: 'FAILURE') 
                {
                    sh'''
                        export PYTHONPATH="$WORKSPACE/src"
                        flake8 --version
                        flake8 --format=pylint --exit-zero src > flake8.out
                    '''
                    recordIssues sourceCodeRetention: 'LAST_BUILD', tools: [flake8(pattern: 'flake8.out')]
                    

                }
            }
        }
        
        stage('Security') 
        {
            steps 
            {
                catchError(buildResult: 'UNSTABLE', stageResult: 'FAILURE') 
                {

                    sh '''#!/bin/bash
                    set -euxo pipefail
    
                    # Crear entorno virtual aislado en el workspace
                    python3 -m venv .venv
    
                    # Activar el entorno virtual
                    source .venv/bin/activate
    
                    # Actualizar pip dentro del venv (esto NO afecta al sistema)
                    pip install --upgrade pip
    
                    # Instalar Bandit dentro del venv
                    pip install bandit
    
                    # Ejecutar Bandit desde el venv
                    bandit --exit-zero -r . -x venv,.venv,tests,build,dist -f txt -o bandit.out 
                    '''
    
                    recordIssues(sourceCodeRetention: 'LAST_BUILD', tools: [bandit(pattern: 'bandit.out')])
                }
            }
        }    
    }
}