pipeline 
{
    agent any

    stages 
    {
        stage('Get Code') 
        {
            steps 
            {
                deleteDir()
                git branch: "main", url: "https://github.com/franbecpin/todo-list-aws.git"                
            }
        } 
        
       
        stage('Deploy')
        {
            steps
            {
                catchError(buildResult: 'UNSTABLE', stageResult: 'FAILURE')
                {
                    sh '''
                        sam build
                        sam validate --region us-east-1 
                        # sam deploy --stack-name todo-list-aws-production --config-file samconfig.toml --no-confirm-changeset --no-fail-on-empty-changeset
                        
                        # usa el entorno 'production' definido en samconfig
                        # sam deploy --config-file samconfig.toml --config-env production  --no-confirm-changeset --no-fail-on-empty-changeset
                        sam deploy --stack-name todo-list-aws-production --config-file samconfig.toml --no-confirm-changeset --no-fail-on-empty-changeset
                        '''
                }
            }
        }
        
        stage('Rest Test'){
         steps
            {
                catchError(buildResult: 'UNSTABLE', stageResult: 'FAILURE')
                {
                    script {
                        def BASE_URL = sh( script: "aws cloudformation describe-stacks --stack-name todo-list-aws --query 'Stacks[0].Outputs[?OutputKey==`BaseUrlApi`].OutputValue' --region us-east-1 --output text",
                            returnStdout: true)
                        echo "$BASE_URL"
                        echo 'Initiating Rest Tests'
                        
                        // Ejecutar pytest con BASE_URL exportada al entorno
                        withEnv(["BASE_URL=${BASE_URL}"]) {
                            sh '''
                                set PYTHONPATH=%WORKSPACE%
                                # pytest test/integration/todoApiTest.py -v --junitxml=pytest.xml
                                pytest test/integration/todoApiTest.py -v --junitxml=pytest.xml -m "not destructive"
                            '''
                        }

                    }
                    
                }
            }    
        }
        
            
        
    }
}

